name: stereo_matching
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python >=3.6
  - cudatoolkit=10.0
  - cudnn=7.6.5
  - pytorch=1.2.0
  - torchvision=0.4.0
  - pip
  - pip:
      - opencv-python
      - rospkg
      - catkin_pkg
      - empy
      - numpy
